# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vQxrPfRqqsQphkhXcq18x25YVTo3Qel
"""

from flask import Flask, request, jsonify
from transformers import pipeline
import psycopg2
import os

app = Flask(__name__)

# Huggingface pipeline
classifier = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

@app.route('/')
def index():
    return "Sentiment Analysis API çalışıyor!"

@app.route('/analyze', methods=['POST'])
def analyze():
    try:
        data = request.get_json()
        text = data['text']
        result = classifier(text)[0]
        label = result['label']
        score = float(result['score'])

        # PostgreSQL bağlantısı
        conn = psycopg2.connect(
            host=os.environ['POSTGRES_HOST'],
            dbname=os.environ['POSTGRES_DB'],
            user=os.environ['POSTGRES_USER'],
            password=os.environ['POSTGRES_PASSWORD']
        )
        cur = conn.cursor()
        cur.execute("CREATE TABLE IF NOT EXISTS analyses (id SERIAL PRIMARY KEY, text TEXT, label TEXT, score REAL)")
        cur.execute("INSERT INTO analyses (text, label, score) VALUES (%s, %s, %s)", (text, label, score))
        conn.commit()
        cur.close()
        conn.close()

        return jsonify({"label": label, "score": score})

    except Exception as e:
        print("Error:", str(e))
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)

